//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMenu.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menus
    {
        public string MenuCode { get; set; }
        public string MenuName { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
    }
}
